#!/usr/bin/env bash

dir="/etc/nix-darwin"
file="$dir/flake.nix"

error()      { >&2 printf "Error: %s\n" "$1";         exit 1; }
impossible() { >&2 printf "%s\n" "Assertion failed!"; exit 2; }
section()    { printf "\n[%s]\n" "$1"; }
status()     { printf ".%s\n"    "$1"; }
sudo_()      { sudo sh -c 'umask 0002 && exec "$@"' sh "$@"; }

git_is_clean() {
  git diff --quiet && \
  git diff --cached --quiet && \
  [ -z "$(git ls-files --others --exclude-standard)" ]
}
git_installed()    { command -v git > /dev/null; }
conf_is_git_repo() { [ -d "$dir/.git" ]; }
conf_present()     { [ -f "$file" ]; }


#### Main Script
section "Checking Script Dependencies"
git_installed    || error "git not installed."
conf_is_git_repo || error "git repository not initialized in $dir"
conf_present     || error "$file does not exist."
(
  cd "$dir" || impossible

  section "Preconfiguration Steps"
  status "Checking git for updates..."
  if git_is_clean
  then
    status "Pulling updates before editing..."
    git pull || error "Cannot pull update from git repository..."
  fi

  section "Opening editor"
  nvim "$dir"
  status "Editing complete."

  section "Post-configuration Steps"
  if git_is_clean
  then
    status "No changes to $dir."
  else
    status "Staging all changes..."
    git add -A || error "Failed to stage changes."
    status "Updating Nix..."
    nix flake update --no-warn-dirty      || error "Flake update failed after edit."
    sudo_ darwin-rebuild switch --flake . || error "Build failed after edit."
    status "Success. Committing to git."
    git commit              || error "Commit failed."
    git push -u origin main || error "Push failed."
  fi
)

