#!/usr/bin/env bash

dir="/etc/nix-darwin"
file="$dir/flake.nix"

run-update() 
(
  cd "$dir"
  if git diff --quiet -- flake.nix
  then
    echo "No changes to $file."
    return 0
  fi

  printf "\n%s\n" "Updating Nix..."
  if sudo nix flake update && sudo darwin-rebuild switch --flake .
  then
    printf "\n%s\n" "Committing to git."
    git add flake.nix
    git commit -m "Update on $(date)."
    git push -u origin main
  else
    return 1
  fi
)

command -v git > /dev/null || { echo "Error: git not installed."; exit 1; }
[ -d "$dir/.git" ] || { echo "Error: git repository not initialized in $dir"; exit 1; }
[ -f "$file" ] || { echo "Error: $file does not exist."; exit 1; }

echo "Opening editor..."
sudo nvim "$file"

run-update

